name: .NET Core

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: Publish
      run: dotnet publish ./Bloggen.Net/Bloggen.Net.csproj -c Release -o deploy
    - name: Tar project file
      run: tar -czf ${{ env.RELEASE_VERSION }}.tar.gz deploy
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        draft: true
        # Newline-delimited list of path globs for asset files to upload
        files: ${{ env.RELEASE_VERSION }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
